name: Update Algolia Search Index
on:
    workflow_call:
    workflow_dispatch:

jobs:
    update-algolia:
        name: Update Algolia Search Index
        runs-on: ubuntu-latest
        steps:
            - name: Update Algolia search index
              uses: algolia/algoliasearch-crawler-github-actions@v1
              id: crawler_push
              with:
                  crawler-name: "Docs"
                  crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
                  crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
                  # "If you already have a crawler set up in Algolia, you can skip them. But the IDE says no"
                  algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
                  algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
                  site-url: "https://docs.bloomlibrary.org"
